name: mimics_env
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - netcdf-fortran
  - xarray
  - pandas
  - matplotlib
  - jupyterlab
  - netcdf4
  - seaborn
